# Generated by Django 4.2.23 on 2025-08-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
