# Generated by Django 4.2.23 on 2025-08-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_image_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tag',
            new_name='tags',
        ),
    ]
